import type { ControlledPlaybook } from "@/lib/executor/playbooks/types";

const leadInputProperties = {
  company: { type: "string" },
  contact: { type: "string" },
  inquiryChannel: { type: "string" },
  preferredLanguage: { type: "string" },
  productLine: { type: "string" },
  need: { type: "string" },
  budget: { type: "string" },
  timing: { type: "string" },
};

export const salesPipelinePlaybook: ControlledPlaybook = {
  id: "sales-pipeline-v1",
  title: "Sales Pipeline Controlled Runtime",
  scenarioId: "sales-pipeline",
  version: "1.0.0",
  triggerTypes: ["inbound_message", "schedule", "web_form", "manual"],
  resultAssets: ["sales_asset", "knowledge_asset"],
  steps: [
    {
      id: "intake",
      title: "收集询盘字段",
      mode: "assist",
      purpose: "把客户询盘整理成后续步骤可消费的结构化输入。",
      inputSchema: {
        type: "object",
        properties: leadInputProperties,
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["summary", "missingFields", "normalizedLead"],
        properties: {
          summary: { type: "string" },
          missingFields: { type: "array", items: { type: "string" } },
          normalizedLead: { type: "object", properties: leadInputProperties },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "human_ask"],
      requiresApproval: false,
      acceptanceCriteria: [
        "输出必须列出缺失字段。",
        "不得编造价格、交期或客户背景。",
        "必须保留来源渠道和产品线。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "workflow_run", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "qualify",
      title: "判断线索优先级",
      mode: "assist",
      purpose: "判断线索是否值得进入跟进草稿阶段。",
      inputSchema: {
        type: "object",
        required: ["normalizedLead"],
        properties: {
          normalizedLead: { type: "object", properties: leadInputProperties },
          missingFields: { type: "array", items: { type: "string" } },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["priority", "reasons", "risks", "nextAction"],
        properties: {
          priority: { enum: ["high", "medium", "low", "blocked"] },
          reasons: { type: "array", items: { type: "string" } },
          risks: { type: "array", items: { type: "string" } },
          nextAction: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "knowledge_search"],
      requiresApproval: false,
      acceptanceCriteria: [
        "必须给出优先级。",
        "必须列出判断理由和风险。",
        "缺失关键信息时 priority 应为 blocked 或 medium 以下。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "sales_asset", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "draft_outreach",
      title: "生成跟进草稿",
      mode: "assist",
      purpose: "生成可供人工审核的客户跟进邮件或话术。",
      inputSchema: {
        type: "object",
        required: ["normalizedLead", "priority", "nextAction"],
        properties: {
          normalizedLead: { type: "object", properties: leadInputProperties },
          priority: { type: "string" },
          nextAction: { type: "string" },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["subject", "body", "assumptions", "needsHumanCheck"],
        properties: {
          subject: { type: "string" },
          body: { type: "string" },
          assumptions: { type: "array", items: { type: "string" } },
          needsHumanCheck: { type: "array", items: { type: "string" } },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "knowledge_search"],
      requiresApproval: false,
      acceptanceCriteria: [
        "草稿不得承诺未确认价格或交期。",
        "必须标出需要人工确认的假设。",
        "必须包含一个明确下一步动作。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "draft", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "human_review",
      title: "人工审核跟进内容",
      mode: "review",
      purpose: "人工确认草稿中的事实、语气、风险和下一步动作。",
      inputSchema: {
        type: "object",
        required: ["subject", "body"],
        properties: {
          subject: { type: "string" },
          body: { type: "string" },
          assumptions: { type: "array", items: { type: "string" } },
          needsHumanCheck: { type: "array", items: { type: "string" } },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["approved", "approvedBody", "reviewNotes"],
        properties: {
          approved: { type: "boolean" },
          approvedBody: { type: "string" },
          reviewNotes: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["human_ask"],
      requiresApproval: true,
      acceptanceCriteria: [
        "必须由人工批准后才能继续写回。",
        "拒绝时不得进入 writeback。",
        "审批记录必须进入 trace。",
      ],
      toolCalls: [{ toolName: "human_ask" }],
      writesTo: [{ target: "workflow_run", when: "after_approval" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "writeback",
      title: "写回销售资产",
      mode: "manual",
      purpose: "把已批准结果写回销售资产和知识资产。",
      inputSchema: {
        type: "object",
        required: ["approved", "approvedBody"],
        properties: {
          approved: { type: "boolean" },
          approvedBody: { type: "string" },
          reviewNotes: { type: "string" },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["salesAssetUpdated", "knowledgeAssetCandidate"],
        properties: {
          salesAssetUpdated: { type: "boolean" },
          knowledgeAssetCandidate: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["human_ask"],
      requiresApproval: true,
      acceptanceCriteria: [
        "只允许写回已批准内容。",
        "必须标记资产来源 workflowRunId。",
        "不得把未确认假设写入高信任知识资产。",
      ],
      toolCalls: [{ toolName: "human_ask" }],
      writesTo: [
        { target: "sales_asset", when: "after_approval" },
        { target: "knowledge_asset", when: "after_approval" },
        { target: "workflow_run", when: "after_approval" },
      ],
      onFailure: { action: "fail_run" },
    },
  ],
};
