import type { ControlledPlaybook } from "@/lib/executor/playbooks/types";

const issueInputProperties = {
  customer: { type: "string" },
  channel: { type: "string" },
  subject: { type: "string" },
  issue: { type: "string" },
  orderId: { type: "string" },
  productLine: { type: "string" },
  language: { type: "string" },
};

export const supportResolutionPlaybook: ControlledPlaybook = {
  id: "support-resolution-v1",
  title: "Support Resolution Controlled Runtime",
  scenarioId: "support-ops",
  version: "1.0.0",
  triggerTypes: ["inbound_message", "manual"],
  resultAssets: ["support_asset", "knowledge_asset", "draft", "workflow_run"],
  steps: [
    {
      id: "intake",
      title: "收集客户问题",
      mode: "assist",
      purpose: "把客服消息整理成后续步骤可消费的结构化问题上下文。",
      inputSchema: {
        type: "object",
        properties: issueInputProperties,
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["summary", "missingFields", "normalizedIssue"],
        properties: {
          summary: { type: "string" },
          missingFields: { type: "array", items: { type: "string" } },
          normalizedIssue: { type: "object", properties: issueInputProperties },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "human_ask"],
      requiresApproval: false,
      acceptanceCriteria: [
        "输出必须列出缺失字段。",
        "不得编造订单、承诺、退款或 SLA。",
        "必须保留客户、渠道和原始问题主题。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "workflow_run", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "classify",
      title: "分类问题和风险",
      mode: "assist",
      purpose: "判断问题类型、优先级、风险和缺失信息。",
      inputSchema: {
        type: "object",
        required: ["normalizedIssue"],
        properties: {
          normalizedIssue: { type: "object", properties: issueInputProperties },
          missingFields: { type: "array", items: { type: "string" } },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["category", "priority", "risks", "nextAction"],
        properties: {
          category: { type: "string" },
          priority: { enum: ["urgent", "high", "normal", "low", "blocked"] },
          risks: { type: "array", items: { type: "string" } },
          missingInfo: { type: "array", items: { type: "string" } },
          nextAction: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "knowledge_search"],
      requiresApproval: false,
      acceptanceCriteria: [
        "必须给出问题分类和优先级。",
        "必须列出风险和缺失信息。",
        "退款、赔付、法律、公开投诉类问题必须标记风险。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "support_asset", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "draft_reply",
      title: "生成客服回复草稿",
      mode: "assist",
      purpose: "生成可供人工审核的客服回复草稿。",
      inputSchema: {
        type: "object",
        required: ["normalizedIssue", "category", "priority", "nextAction"],
        properties: {
          normalizedIssue: { type: "object", properties: issueInputProperties },
          category: { type: "string" },
          priority: { type: "string" },
          nextAction: { type: "string" },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["subject", "body", "tone", "needsHumanCheck"],
        properties: {
          subject: { type: "string" },
          body: { type: "string" },
          tone: { type: "string" },
          assumptions: { type: "array", items: { type: "string" } },
          needsHumanCheck: { type: "array", items: { type: "string" } },
        },
        additionalProperties: false,
      },
      allowedTools: ["llm_generate", "knowledge_search"],
      requiresApproval: false,
      acceptanceCriteria: [
        "回复不得承诺未确认退款、赔付、交期或政策例外。",
        "必须标出需要人工确认的内容。",
        "必须包含明确下一步动作。",
      ],
      toolCalls: [{ toolName: "llm_generate" }],
      writesTo: [{ target: "draft", when: "on_success" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "human_review",
      title: "人工审核客服回复",
      mode: "review",
      purpose: "人工确认回复事实、语气、风险边界和下一步动作。",
      inputSchema: {
        type: "object",
        required: ["subject", "body"],
        properties: {
          subject: { type: "string" },
          body: { type: "string" },
          tone: { type: "string" },
          assumptions: { type: "array", items: { type: "string" } },
          needsHumanCheck: { type: "array", items: { type: "string" } },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["approved", "approvedReply", "reviewNotes", "nextAction"],
        properties: {
          approved: { type: "boolean" },
          approvedReply: { type: "string" },
          reviewNotes: { type: "string" },
          nextAction: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["human_ask"],
      requiresApproval: true,
      acceptanceCriteria: [
        "必须由人工批准后才能继续写回。",
        "拒绝时不得进入 writeback。",
        "审批记录必须进入 trace。",
      ],
      toolCalls: [{ toolName: "human_ask" }],
      writesTo: [{ target: "workflow_run", when: "after_approval" }],
      onFailure: { action: "await_human" },
    },
    {
      id: "writeback",
      title: "写回客服资产",
      mode: "manual",
      purpose: "把已批准客服处理结果写回 support asset 和 knowledge asset。",
      inputSchema: {
        type: "object",
        required: ["approved", "approvedReply"],
        properties: {
          approved: { type: "boolean" },
          approvedReply: { type: "string" },
          reviewNotes: { type: "string" },
          nextAction: { type: "string" },
        },
        additionalProperties: true,
      },
      outputSchema: {
        type: "object",
        required: ["supportAssetUpdated", "knowledgeAssetCandidate", "faqCandidate"],
        properties: {
          supportAssetUpdated: { type: "boolean" },
          knowledgeAssetCandidate: { type: "string" },
          faqCandidate: { type: "string" },
        },
        additionalProperties: false,
      },
      allowedTools: ["human_ask"],
      requiresApproval: true,
      acceptanceCriteria: [
        "只允许写回已批准内容。",
        "必须标记资产来源 workflowRunId。",
        "不得把未确认政策例外写入高信任知识资产。",
      ],
      toolCalls: [{ toolName: "human_ask" }],
      writesTo: [
        { target: "support_asset", when: "after_approval" },
        { target: "knowledge_asset", when: "after_approval" },
        { target: "workflow_run", when: "after_approval" },
      ],
      onFailure: { action: "fail_run" },
    },
  ],
};
